const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");

const mechanicSchema = new mongoose.Schema(
  {
    garage: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Agent",
      required: false, // Assigned garage (Agent/Garage record)
    },
    fullName: {
      type: String,
      required: true,
      trim: true,
    },
    phone: {
      type: String,
      required: true,
      unique: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    password: {
      type: String,
      required: true,
    },
    skills: {
      type: [String], // Example: ["Car Repair", "Bike Engine", "Oil Change"]
      default: [],
    },
    experienceYears: {
      type: Number,
      default: 0,
    },
    certifications: {
      type: [String], // Optional certifications
      default: [],
    },
    status: {
      type: String,
      enum: ["pending", "verified", "rejected"],
      default: "pending", // Admin verifies mechanic
    },
    rating: {
      type: Number,
      default: 0,
      min: 0,
      max: 5,
    },
    totalReviews: {
      type: Number,
      default: 0,
    },
    isBusy: {
      type: Boolean,
      default: false,
    },
    uniqueId: {
      type: String, // Generated by system when verified
      unique: true,
      sparse: true, // allows null before verification
    },
  },
  { timestamps: true }
);

// Hash password before saving
mechanicSchema.pre("save", async function (next) {
  if (!this.password || !this.isModified("password")) return next();
  this.password = await bcrypt.hash(this.password, 10);
  next();
});

// Compare password method
mechanicSchema.methods.comparePassword = async function (candidatePassword) {
  if (!this.password) return false;
  return bcrypt.compare(candidatePassword, this.password);
};

module.exports = mongoose.model("Mechanic", mechanicSchema);